(function(){
  const API='https://msfkpwwqrpbmgdtlbwdo.supabase.co/functions/v1/gas-api';
  const DASH_API='https://msfkpwwqrpbmgdtlbwdo.supabase.co/functions/v1/dashboard-fast';
  const local={getLogoData:()=>({lkpp:'./logo-lkpp.png',labusel:'./logo-labusel.png',ukpbj:'./logo-ukpbj.png'})};
  const aliases={authenticate:'login',registerAccount:'daftarUser'};
  const DASH_CACHE_KEY='monitoring_dashboard_cache_v1';
  const DASH_IDS=['pimpinanTotalProyek','pimpinanTotalNilai','pimpinanBerjalan','pimpinanSelesai','pimpinanRataProgres'];
  const GENERAL_IDS=['statProyek','statLaporan'];
  let activeRunner=null;
  let dashboardDataReady=false;
  let latestDashboardData=null;
  function cacheIsUseful(data){if(!data||data.success===false)return false;const n=Number(data.totalProyek);const list=Array.isArray(data.daftar)?data.daftar:[];return Number.isFinite(n)&&(n>0||list.length>0||Number(data.totalNilai)>0||Number(data.totalLaporan)>0);}
  function getDashboardCache(){try{const raw=localStorage.getItem(DASH_CACHE_KEY);if(!raw)return null;const parsed=JSON.parse(raw);if(!parsed||!cacheIsUseful(parsed.data))return null;return parsed.data;}catch(e){return null;}}
  function saveDashboardCache(data){try{if(data&&data.success!==false)localStorage.setItem(DASH_CACHE_KEY,JSON.stringify({savedAt:Date.now(),data:data}));}catch(e){}}
  function setText(id,value){const el=document.getElementById(id);if(!el)return;const next=String(value);if(el.textContent!==next)el.textContent=next;}
  function paintDashboardData(data){if(!data||data.success===false)return;latestDashboardData=data;dashboardDataReady=true;setText('statProyek',Number.isFinite(Number(data.totalProyek))?Number(data.totalProyek):'—');setText('statLaporan',Number.isFinite(Number(data.totalLaporan))?Number(data.totalLaporan):'—');setText('pimpinanTotalProyek',Number.isFinite(Number(data.totalProyek))?Number(data.totalProyek):'—');setText('pimpinanTotalNilai',data.totalNilaiDisplay||'—');setText('pimpinanBerjalan',Number.isFinite(Number(data.proyekBerjalan))?Number(data.proyekBerjalan):'—');setText('pimpinanSelesai',Number.isFinite(Number(data.proyekSelesai))?Number(data.proyekSelesai):'—');setText('pimpinanRataProgres',Number.isFinite(Number(data.rataRataProgres))?Number(data.rataRataProgres)+'%':'—');}
  function paintCachedDashboard(){const data=getDashboardCache();if(!data)return;paintDashboardData(data);}
  function isZeroPlaceholder(value){return /^(0|Rp 0|0%)$/.test(String(value||'').trim());}
  function preventZeroFlash(){const allIds=DASH_IDS.concat(GENERAL_IDS);const fix=function(){if(dashboardDataReady)return;allIds.forEach(function(id){const el=document.getElementById(id);if(el&&isZeroPlaceholder(el.textContent))el.textContent='—';});};const start=function(){fix();const observer=new MutationObserver(function(mutations){mutations.forEach(function(m){if(m.type!=='characterData'&&m.type!=='childList')return;const target=m.target&&m.target.nodeType===3?m.target.parentElement:m.target;if(!target)return;const el=target.closest?target.closest('#statProyek,#statLaporan,#pimpinanTotalProyek,#pimpinanTotalNilai,#pimpinanBerjalan,#pimpinanSelesai,#pimpinanRataProgres'):null;if(!el)return;if(dashboardDataReady&&latestDashboardData)paintDashboardData(latestDashboardData);else if(isZeroPlaceholder(el.textContent))el.textContent='—';});});observer.observe(document.body,{subtree:true,childList:true,characterData:true});};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();}
  paintCachedDashboard();
  preventZeroFlash();
  function makeRunner(){let ok=null,bad=null;const target={};const runner=new Proxy(target,{get(_,name){if(name==='withSuccessHandler')return fn=>{ok=typeof fn==='function'?fn:null;return runner;};if(name==='withFailureHandler')return fn=>{bad=typeof fn==='function'?fn:null;return runner;};return(...args)=>{const success=ok,failure=bad;ok=null;bad=null;if(name==='getPimpinanDashboardData'&&success){const cached=getDashboardCache();if(cached){paintDashboardData(cached);try{success(cached);}catch(e){console.error(e);}}}return new Promise(async resolve=>{let lastError=null;for(let attempt=1;attempt<=2;attempt++){try{if(name==='getLogoData'){const value=local.getLogoData();if(success)success(value);resolve(value);return;}const fn=aliases[name]||name;const endpoint=name==='getPimpinanDashboardData'?DASH_API:API;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),30000);let res;try{res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({function:String(fn),args}),signal:controller.signal,cache:'no-store'});}finally{clearTimeout(timer);}const text=await res.text();let data;try{data=JSON.parse(text);}catch(e){throw new Error(text||'Respons backend tidak valid.');}if(!res.ok){const err=new Error(data&&data.message?data.message:'Request gagal.');err.httpStatus=res.status;throw err;}if(name==='getPimpinanDashboardData'){saveDashboardCache(data);paintDashboardData(data);}if(success)success(data);resolve(data);return;}catch(err){lastError=err;const retryable=err&&(err.name==='AbortError'||err.httpStatus===408||err.httpStatus===429||err.httpStatus>=500);if(!retryable||attempt===2)break;await new Promise(r=>setTimeout(r,700));}}const message=lastError&&lastError.name==='AbortError'?'Koneksi ke server timeout. Silakan coba lagi.':(lastError&&lastError.message?lastError.message:String(lastError));if(failure)failure({message});else console.error(message);resolve({success:false,message});});};}});return runner;}
  function installBridge(){window.google=window.google||{};window.google.script=window.google.script||{};activeRunner=makeRunner();const scriptObj=window.google.script;const desc=Object.getOwnPropertyDescriptor(scriptObj,'run');if(!desc||desc.configurable){Object.defineProperty(scriptObj,'run',{configurable:true,enumerable:true,get:function(){return activeRunner;},set:function(){activeRunner=makeRunner();}});}}
  installBridge();window.__supabaseBridge=makeRunner;window.__installSupabaseBridge=installBridge;setTimeout(installBridge,0);setTimeout(installBridge,100);setTimeout(installBridge,500);document.addEventListener('DOMContentLoaded',function(){installBridge();paintCachedDashboard();},{once:true});
  function loadMobileCardCss(){if(!window.matchMedia||!window.matchMedia('(max-width:760px)').matches)return;if(document.getElementById('mobileCardCss'))return;const preload=document.createElement('style');preload.id='mobileCardCssPreload';preload.textContent='#dashboardView .pimpinan-table-wrap{visibility:hidden!important;}';document.head.appendChild(preload);const link=document.createElement('link');link.id='mobileCardCss';link.rel='stylesheet';link.href='./mobile-only.css?v=20260826-02';link.onload=function(){const s=document.getElementById('mobileCardCssPreload');if(s)s.remove();};link.onerror=function(){const s=document.getElementById('mobileCardCssPreload');if(s)s.remove();};document.head.appendChild(link);setTimeout(function(){const s=document.getElementById('mobileCardCssPreload');if(s)s.remove();},5000);}
  loadMobileCardCss();document.addEventListener('DOMContentLoaded',loadMobileCardCss,{once:true});
  document.addEventListener('DOMContentLoaded',function(){if(!window.matchMedia||!window.matchMedia('(max-width:760px)').matches)return;if(typeof window.renderProgressDetail!=='function')return;const originalRender=window.renderProgressDetail;window.renderProgressDetail=function(mingguList){if(!Array.isArray(mingguList))return originalRender(mingguList);const body=document.getElementById('progressDetailBody');if(!body)return originalRender(mingguList);body.innerHTML='';if(!mingguList.length){body.innerHTML='<div class="empty">Belum ada laporan mingguan untuk proyek ini.</div>';return;}mingguList.forEach(function(item){const laporan=item&&item.laporan||{};const block=document.createElement('div');block.className='week-block';const head=document.createElement('div');head.className='week-head';const weekTitle=document.createElement('div');weekTitle.className='week-title';weekTitle.textContent='Minggu ke-'+(item.mingguKe||laporan.mingguKe||'-');const progress=document.createElement('div');progress.className='week-progress';progress.textContent=(laporan.progres||'0')+'%';head.appendChild(weekTitle);head.appendChild(progress);block.appendChild(head);const meta=document.createElement('div');meta.className='week-meta';meta.textContent='Tanggal: '+(laporan.tanggal||'-')+' | Penyedia: '+(laporan.namaPenyedia||'-')+' | Dibuat oleh: '+(laporan.dibuatOleh||'-');block.appendChild(meta);if(laporan.keterangan){const note=document.createElement('div');note.className='week-note';note.textContent='Keterangan: '+laporan.keterangan;block.appendChild(note);}const photos=Array.isArray(item.foto)?item.foto:[];if(!photos.length){const emptyPhoto=document.createElement('div');emptyPhoto.className='no-photo';emptyPhoto.style.marginTop='10px';emptyPhoto.textContent='Belum ada foto dokumentasi pada minggu ini.';block.appendChild(emptyPhoto);}else{const grid=document.createElement('div');grid.className='week-photo-grid';grid.style.display='block';grid.style.width='100%';grid.style.marginTop='12px';photos.forEach(function(photo,index){const href=photo&&photo.linkFoto?photo.linkFoto:'';if(!href)return;const card=document.createElement('div');card.className='week-photo-card';card.style.width='100%';card.style.margin='0 0 14px 0';card.style.padding='0';card.style.border='0';card.style.background='transparent';card.style.boxShadow='none';const img=document.createElement('img');img.src=href;img.alt='Foto dokumentasi minggu ke-'+(item.mingguKe||'-')+' nomor '+(index+1);img.loading='lazy';img.style.display='block';img.style.width='100%';img.style.height='auto';img.style.maxWidth='100%';img.style.objectFit='contain';img.style.borderRadius='10px';img.style.background='#f4f7f9';card.appendChild(img);grid.appendChild(card);});block.appendChild(grid);}body.appendChild(block);});};},{once:true});
  function loadSafeTheme(){if(document.getElementById('safeVisualTheme'))return;const link=document.createElement('link');link.id='safeVisualTheme';link.rel='stylesheet';link.href='./theme-safe-preview.css?v=20260826-02';document.head.appendChild(link);}loadSafeTheme();document.addEventListener('DOMContentLoaded',loadSafeTheme,{once:true});
  /* ADMIN DASHBOARD FIX: force the fast dashboard fetch after the existing dashboard opens. */
  document.addEventListener('DOMContentLoaded',function(){var tries=0;var timer=setInterval(function(){tries++;if(typeof window.bukaDashboard==='function'){clearInterval(timer);if(window.__adminDashboardStatsFixApplied)return;window.__adminDashboardStatsFixApplied=true;var original=window.bukaDashboard;window.bukaDashboard=function(){original.apply(this,arguments);setTimeout(function(){try{if(window.currentUser&&String(window.currentUser.role||'').toUpperCase()==='ADMIN'&&typeof window.loadPimpinanDashboard==='function')window.loadPimpinanDashboard();}catch(e){console.error(e);}},50);};}if(tries>=200)clearInterval(timer);},100);},{once:true});
})();
